<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>capnp</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Cap'n Proto</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\@(([0-9]+)|(0x[0-9a-fA-F]+))\b</string>
			<key>name</key>
			<string>keyword.type.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(struct|enum|interface|extends|const|union|using|import|annotation)\b</string>
			<key>name</key>
			<string>keyword.type.capnp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.pound.capnp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(0x)?"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=:)\s*(Void|Bool|Int8|Int16|Int32|Int64|UInt8|UInt16|UInt32|UInt64|Float32|Float64|Text|Data|List)\b</string>
			<key>name</key>
			<string>constant.language.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0x[0-9a-fA-F]+)|((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(inf|nan|void|true|false)(?!\s*@)\b</string>
			<key>name</key>
			<string>constant.other.capnp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.capnp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=struct|enum|annotation)\s+([a-zA-Z0-9_]+)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.capnp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.pound.capnp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.capnp</string>
	<key>uuid</key>
	<string>6FD716E0-5D88-11E4-B689-0800200C9A66</string>
</dict>
</plist>
